### ISSUE TITLE
our ircbot no longer works under django 3

### ISSUE THREAD

**Issue by tykling** [bornhack/bornhack-website#446]
Something happens as soon as we try to access a queryset in https://github.com/bornhack/bornhack-website/blob/master/src/ircbot/irc3module.py#L216

I think we need to wrap all database access in a sync_to_async thing?

```
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker ERROR asyncio    Exception in callback Plugin.do_stuff()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker handle: <TimerHandle when=665141.48041529 Plugin.do_stuff()>
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker Traceback (most recent call last):
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     self._context.run(self._callback, *self._args)
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 119, in do_stuff
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     self.bot.check_irc_channels()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 171, in check_irc_channels
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     desired_channel_list = self.bot.get_desired_channel_list()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 193, in get_desired_channel_list
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     desired_channel_list = self.get_managed_team_channels()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 216, in get_managed_team_channels
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     return list(pubchans) + list(privchans)
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 276, in __iter__
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     self._fetch_all()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     self._result_cache = list(self._iterable_class(self))
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 184, in __iter__
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1096, in results_iter
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     cursor = self.connection.cursor()
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/django/utils/asyncio.py", line 24, in inner
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker     raise SynchronousOnlyOperation(message)
Feb 12 17:25:52 wwwprod3 /supervisord[23136]: ircworker django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by tykling** [comment]
commit 235cb9683b46b27fd1291465a519b9b663bc843 changed the error but the bot still doesn't work:

Feb 23 11:18:38 wwwprod3 /supervisord[23136]: ircworker [23/Feb/2020 12:18:38] bornhack.ircbot.irc3module.handle_nickserv_privmsg() DEBUG Got a message from NickServ
Feb 23 11:18:38 wwwprod3 /supervisord[23136]: ircworker [23/Feb/2020 12:18:38] bornhack.ircbot.irc3module.handle_nickserv_privmsg() DEBUG Unhandled NickServ message: You are now identified for ^BBornHack^B.
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker /usr/local/www/django/src/ircbot/irc3module.py:121: RuntimeWarning: coroutine 'SyncToAsync.__call__' was never awaited
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker   sync_to_async(self.bot.check_irc_channels)()
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker /usr/local/www/django/src/ircbot/irc3module.py:122: RuntimeWarning: coroutine 'SyncToAsync.__call__' was never awaited
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker   sync_to_async(self.bot.fix_missing_acls)()
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker /usr/local/www/django/src/ircbot/irc3module.py:123: RuntimeWarning: coroutine 'SyncToAsync.__call__' was never awaited
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker   sync_to_async(self.bot.get_outgoing_messages)()
Feb 23 11:18:48 wwwprod3 /supervisord[23136]: ircworker RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by valberg** [comment]
Ah! Hopefully https://github.com/bornhack/bornhack-website/commit/7e2981e855496ce7b9c8757733ad02fe3614961f fixes the fix :sweat_smile:

**Comment by tykling** [comment]
unfortunately still no luck:
```
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker SyntaxError: 'await' outside async function
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 19:55:49] bornhack.utils.management.commands.run_managepy_worker.handle() ERROR Got exception inside do_work for <module 'ircbot.ircworker' from '/usr/local/www/django/src/ircbot/ircworker.py'>
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker Traceback (most recent call last):
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/utils/management/commands/run_managepy_worker.py", line 58, in handle
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     getattr(self.workermodule, "do_work")()
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/ircworker.py", line 37, in do_work
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     raise E
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/ircworker.py", line 34, in do_work
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     irc3.IrcBot(**config).run(forever=True)
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/__init__.py", line 119, in __init__
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     super(IrcBot, self).__init__(*ini, **config)
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/base.py", line 115, in __init__
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     self.include(*self.config.get('includes', []))
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/base.py", line 206, in include
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     module = utils.maybedotted(module)
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/utils.py", line 330, in maybedotted
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     mod = importlib.import_module(name)
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     return _bootstrap._gcd_import(name[level:], package, level)
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 860, in get_code
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 121
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     await sync_to_async(self.bot.check_irc_channels)()
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker     ^
Mar 10 18:55:49 wwwprod3 /supervisord[23136]: ircworker SyntaxError: 'await' outside async function
```

**Comment by tykling** [comment]
no backtrace but no success either, it stops outputting here:
```
Mar 10 19:18:47 wwwprod3 /supervisord[23136]: ircworker /usr/local/lib/python3.7/asyncio/events.py:88: RuntimeWarning: coroutine 'Plugin.do_stuff' was never awaited
Mar 10 19:18:47 wwwprod3 /supervisord[23136]: ircworker   self._context.run(self._callback, *self._args)
Mar 10 19:18:47 wwwprod3 /supervisord[23136]: ircworker RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by tykling** [comment]
```
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:09:36] bornhack.utils.management.commands.run_managepy_worker.handle() ERROR Got exception inside do_work for <module 'ircbot.ircworker' from '/usr/local/www/django/src/ircbot/ircworker.py'>
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker Traceback (most recent call last):
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/utils/management/commands/run_managepy_worker.py", line 58, in handle
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     getattr(self.workermodule, "do_work")()
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/ircworker.py", line 37, in do_work
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     raise E
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/ircworker.py", line 34, in do_work
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     irc3.IrcBot(**config).run(forever=True)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/__init__.py", line 119, in __init__
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     super(IrcBot, self).__init__(*ini, **config)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/base.py", line 115, in __init__
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     self.include(*self.config.get('includes', []))
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/base.py", line 206, in include
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     module = utils.maybedotted(module)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/site-packages/irc3/utils.py", line 330, in maybedotted
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     mod = importlib.import_module(name)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     return _bootstrap._gcd_import(name[level:], package, level)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 860, in get_code
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker   File "/usr/local/www/django/src/ircbot/irc3module.py", line 48
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     await asyncio.sleep(settings.IRCBOT_CHECK_MESSAGE_INTERVAL_SECONDS)
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker     ^
Mar 10 20:09:36 wwwprod3 /supervisord[23136]: ircworker SyntaxError: 'await' outside async function
```

**Comment by tykling** [comment]
```
Mar 10 20:13:08 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:08] bornhack.utils.management.commands.run_managepy_worker.handle() INFO Importing worker module...
Mar 10 20:13:08 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:08] bornhack.utils.management.commands.run_managepy_worker.handle() INFO Connecting signals...
Mar 10 20:13:08 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:08] bornhack.utils.management.commands.run_managepy_worker.handle() INFO Entering main loop...
Mar 10 20:13:08 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:08] bornhack.ircbot.ircworker.do_work() DEBUG Connecting to IRC with the following config: {'nick': 'BornHack', 'autojoins': [], 'host': 'irc.baconsvin.org', 'port': 6697, 'ssl': True, 'timeout': 30, 'flood_burst': 2, 'flood_rate': 1, 'flood_rate_delay': 2, 'includes': ['ircbot.irc3module']}
Mar 10 20:13:09 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:09] bornhack.ircbot.irc3module.connection_made() DEBUG inside connection_made(), kwargs: {}
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker INFO irc3.BornHack Server config: {'STATUSMSG': '@+', 'PREFIX': '(ov)@+', 'CHANTYPES': '&#', 'CHANMODES': 'eIbq,k,flj,CFLPQcgimnprstz', 'WHOX': True, 'FNC': True, 'KNOCK': True, 'ETRACE': True, 'CPRIVMSG': True, 'CNOTICE': True, 'MONITOR': '100', 'SAFELIST': True, 'ELIST': 'CTU', 'EXCEPTS': True, 'INVEX': True, 'CHANLIMIT': '&#:50', 'MAXLIST': 'bqeI:100', 'MODES': '4', 'NETWORK': 'Baconsvin', 'CALLERID': 'g', 'CASEMAPPING': 'rfc1459', 'NICKLEN': '30', 'MAXNICKLEN': '31', 'CHANNELLEN': '50', 'TOPICLEN': '390', 'DEAF': 'D', 'TARGMAX': 'NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR:', 'EXTBAN': '$,acjorsxz', 'CLIENTVER': '3.0'}
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker /usr/local/virtualenv/lib/python3.7/site-packages/irc3/base.py:271: RuntimeWarning: coroutine 'Plugin.server_ready' was never awaited
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker   meth()
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:19] bornhack.ircbot.irc3module.on_privmsg() DEBUG inside on_privmsg(), kwargs: {'mask': 'NickServ!NickServ@services.baconsvin.org', 'event': 'NOTICE', 'target': 'BornHack', 'data': 'This nickname is registered. Please choose a different nickname, or identify via \x02/msg NickServ identify <password>\x02.'}
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:19] bornhack.ircbot.irc3module.handle_nickserv_privmsg() DEBUG Got a message from NickServ
Mar 10 20:13:19 wwwprod3 /supervisord[23136]: ircworker [10/Mar/2020 21:13:19] bornhack.ircbot.irc3module.handle_nickserv_privmsg() DEBUG Unhandled NickServ message: This nickname is registered. Please choose a different nickname, or identify via ^B/msg NickServ identify <password>^B.
```

**Comment by tykling** [comment]
949cb05ae1c3ca47118bf09f9ba28742d76184ac
