### ISSUE TITLE
One particular event CfP gives 500

### ISSUE THREAD

**Issue by benjaoming** [bornhack/bornhack-website#603]
Navigating from:
https://bornhack.dk/bornhack-2020/program/proposals/

...Only this one displays Error 500:
https://bornhack.dk/bornhack-2020/program/proposals/submit/slacking-off/select_person/

(the others work)

**Comment by tykling** [comment]
```
Traceback (most recent call last):
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "./program/mixins.py", line 25, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "./program/views.py", line 792, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/usr/local/virtualenv/lib/python3.7/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
  File "./program/multiform.py", line 196, in __init__
    super(MultiModelForm, self).__init__(*args, **kwargs)
  File "./program/multiform.py", line 64, in __init__
    self.forms[key] = form_class(*fargs, **fkwargs)
  File "./program/forms.py", line 240, in __init__
    f"Unsupported event type '{event_type.name}', don't know which form class to use"

Exception Type: ImproperlyConfigured at /bornhack-2020/program/proposals/submit/slacking-off/
Exception Value: Unsupported event type 'Slacking Off', don't know which form class to use
Request information:
USER: benjamin
```

**Comment by tykling** [comment]
bonus info: I recently renamed from slacking off to recreational event and clearly forgot a few places
